# Generated by Django 4.2.7 on 2023-11-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_csnnades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_mapa', models.CharField(choices=[('Mirage', 'Mirage'), ('Inferno', 'Inferno'), ('Overpass', 'Overpass'), ('Nuke', 'Nuke'), ('Vertigo', 'Vertigo'), ('Anubis', 'Anubis'), ('Ancient', 'Ancient')], max_length=50)),
                ('tipo_granada', models.CharField(choices=[('Smoke', 'Smoke'), ('Flash', 'Flash'), ('HE', 'High Explosive (HE)'), ('Molotov', 'Molotov')], max_length=20)),
                ('bomb', models.CharField(choices=[('Bomb A', 'Bomb A'), ('Bomb B', 'Bomb B'), ('Meio', 'Meio')], max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='VideoPost',
        ),
    ]
