# Generated by Django 4.2.7 on 2023-11-28 15:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_csnnades', '0003_granada_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='granada',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='granada',
            name='link',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
